package kontent.ai.sample.android.kotlin.models;

import java.lang.String;
import java.time.ZonedDateTime;
import java.util.List;
import kontent.ai.delivery.Asset;
import kontent.ai.delivery.ContentItem;
import kontent.ai.delivery.ContentItemMapping;
import kontent.ai.delivery.ElementMapping;
import kontent.ai.delivery.Option;
import kontent.ai.delivery.System;
import kontent.ai.delivery.Taxonomy;

/**
 * This code was generated by a <a href="https://github.com/kontent-ai/java-packages/tree/master/delivery-sdk-generators">delivery-sdk-generators tool</a>
 *
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * For further modifications of the class, create a separate file and extend this class.
 */
@ContentItemMapping("article__copy_")
public class ArticleCopy {
  @ElementMapping("title")
  String title;

  @ElementMapping("subtitle")
  String subtitle;

  @ElementMapping("teaser_image")
  List<Asset> teaserImage;

  @ElementMapping("focal_point__maarten_")
  String focalPointMaarten;

  @ElementMapping("focal_point")
  String focalPoint;

  @ElementMapping("illustrative_image")
  String illustrativeImage;

  @ElementMapping("content")
  String content;

  @ElementMapping("publishing_date")
  ZonedDateTime publishingDate;

  @ContentItemMapping("related_call_to_action__cta_")
  List<ContentItem> relatedCallToActionCta;

  @ElementMapping("analyse_content_integration")
  String analyseContentIntegration;

  @ElementMapping("url")
  String url;

  @ElementMapping("seo_metadata__title")
  String seoMetadataTitle;

  @ElementMapping("seo_metadata__description")
  String seoMetadataDescription;

  @ElementMapping("seo_metadata__keywords")
  String seoMetadataKeywords;

  @ElementMapping("seo_metadata__indexing")
  List<Option> seoMetadataIndexing;

  @ElementMapping("seo_metadata__canonical_tags")
  String seoMetadataCanonicalTags;

  @ElementMapping("seo_metadata__og_type")
  String seoMetadataOgType;

  @ElementMapping("seo_metadata__og_image")
  List<Asset> seoMetadataOgImage;

  @ElementMapping("seo_metadata__old_url__301_redirect_")
  String seoMetadataOldUrl301Redirect;

  @ElementMapping("persona")
  List<Taxonomy> persona;

  @ElementMapping("portfolio")
  List<Taxonomy> portfolio;

  @ElementMapping("holiday_type")
  List<Taxonomy> holidayType;

  @ElementMapping("size_of_the_business")
  List<Taxonomy> sizeOfTheBusiness;

  @ElementMapping("show_content_on")
  List<Option> showContentOn;

  System system;

  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public String getSubtitle() {
    return subtitle;
  }

  public void setSubtitle(String subtitle) {
    this.subtitle = subtitle;
  }

  public List<Asset> getTeaserImage() {
    return teaserImage;
  }

  public void setTeaserImage(List<Asset> teaserImage) {
    this.teaserImage = teaserImage;
  }

  public String getFocalPointMaarten() {
    return focalPointMaarten;
  }

  public void setFocalPointMaarten(String focalPointMaarten) {
    this.focalPointMaarten = focalPointMaarten;
  }

  public String getFocalPoint() {
    return focalPoint;
  }

  public void setFocalPoint(String focalPoint) {
    this.focalPoint = focalPoint;
  }

  public String getIllustrativeImage() {
    return illustrativeImage;
  }

  public void setIllustrativeImage(String illustrativeImage) {
    this.illustrativeImage = illustrativeImage;
  }

  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public ZonedDateTime getPublishingDate() {
    return publishingDate;
  }

  public void setPublishingDate(ZonedDateTime publishingDate) {
    this.publishingDate = publishingDate;
  }

  public List<ContentItem> getRelatedCallToActionCta() {
    return relatedCallToActionCta;
  }

  public void setRelatedCallToActionCta(List<ContentItem> relatedCallToActionCta) {
    this.relatedCallToActionCta = relatedCallToActionCta;
  }

  public String getAnalyseContentIntegration() {
    return analyseContentIntegration;
  }

  public void setAnalyseContentIntegration(String analyseContentIntegration) {
    this.analyseContentIntegration = analyseContentIntegration;
  }

  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public String getSeoMetadataTitle() {
    return seoMetadataTitle;
  }

  public void setSeoMetadataTitle(String seoMetadataTitle) {
    this.seoMetadataTitle = seoMetadataTitle;
  }

  public String getSeoMetadataDescription() {
    return seoMetadataDescription;
  }

  public void setSeoMetadataDescription(String seoMetadataDescription) {
    this.seoMetadataDescription = seoMetadataDescription;
  }

  public String getSeoMetadataKeywords() {
    return seoMetadataKeywords;
  }

  public void setSeoMetadataKeywords(String seoMetadataKeywords) {
    this.seoMetadataKeywords = seoMetadataKeywords;
  }

  public List<Option> getSeoMetadataIndexing() {
    return seoMetadataIndexing;
  }

  public void setSeoMetadataIndexing(List<Option> seoMetadataIndexing) {
    this.seoMetadataIndexing = seoMetadataIndexing;
  }

  public String getSeoMetadataCanonicalTags() {
    return seoMetadataCanonicalTags;
  }

  public void setSeoMetadataCanonicalTags(String seoMetadataCanonicalTags) {
    this.seoMetadataCanonicalTags = seoMetadataCanonicalTags;
  }

  public String getSeoMetadataOgType() {
    return seoMetadataOgType;
  }

  public void setSeoMetadataOgType(String seoMetadataOgType) {
    this.seoMetadataOgType = seoMetadataOgType;
  }

  public List<Asset> getSeoMetadataOgImage() {
    return seoMetadataOgImage;
  }

  public void setSeoMetadataOgImage(List<Asset> seoMetadataOgImage) {
    this.seoMetadataOgImage = seoMetadataOgImage;
  }

  public String getSeoMetadataOldUrl301Redirect() {
    return seoMetadataOldUrl301Redirect;
  }

  public void setSeoMetadataOldUrl301Redirect(String seoMetadataOldUrl301Redirect) {
    this.seoMetadataOldUrl301Redirect = seoMetadataOldUrl301Redirect;
  }

  public List<Taxonomy> getPersona() {
    return persona;
  }

  public void setPersona(List<Taxonomy> persona) {
    this.persona = persona;
  }

  public List<Taxonomy> getPortfolio() {
    return portfolio;
  }

  public void setPortfolio(List<Taxonomy> portfolio) {
    this.portfolio = portfolio;
  }

  public List<Taxonomy> getHolidayType() {
    return holidayType;
  }

  public void setHolidayType(List<Taxonomy> holidayType) {
    this.holidayType = holidayType;
  }

  public List<Taxonomy> getSizeOfTheBusiness() {
    return sizeOfTheBusiness;
  }

  public void setSizeOfTheBusiness(List<Taxonomy> sizeOfTheBusiness) {
    this.sizeOfTheBusiness = sizeOfTheBusiness;
  }

  public List<Option> getShowContentOn() {
    return showContentOn;
  }

  public void setShowContentOn(List<Option> showContentOn) {
    this.showContentOn = showContentOn;
  }

  public System getSystem() {
    return system;
  }

  public void setSystem(System system) {
    this.system = system;
  }
}
