package kontent.ai.sample.android.kotlin.models;

import java.lang.String;
import java.util.List;
import kontent.ai.delivery.ContentItemMapping;
import kontent.ai.delivery.ElementMapping;
import kontent.ai.delivery.System;

/**
 * This code was generated by a <a href="https://github.com/kontent-ai/java-packages/tree/master/delivery-sdk-generators">delivery-sdk-generators tool</a>
 *
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * For further modifications of the class, create a separate file and extend this class.
 */
@ContentItemMapping("asset")
public class Asset {
  @ElementMapping("name")
  String name;

  @ElementMapping("alt_text")
  String altText;

  @ElementMapping("untitled_asset")
  List<kontent.ai.delivery.Asset> untitledAsset;

  System system;

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getAltText() {
    return altText;
  }

  public void setAltText(String altText) {
    this.altText = altText;
  }

  public List<kontent.ai.delivery.Asset> getUntitledAsset() {
    return untitledAsset;
  }

  public void setUntitledAsset(List<kontent.ai.delivery.Asset> untitledAsset) {
    this.untitledAsset = untitledAsset;
  }

  public System getSystem() {
    return system;
  }

  public void setSystem(System system) {
    this.system = system;
  }
}
