package kontent.ai.sample.android.kotlin.models;

import java.lang.String;
import java.util.List;
import kontent.ai.delivery.Asset;
import kontent.ai.delivery.ContentItem;
import kontent.ai.delivery.ContentItemMapping;
import kontent.ai.delivery.ElementMapping;
import kontent.ai.delivery.System;

/**
 * This code was generated by a <a href="https://github.com/kontent-ai/java-packages/tree/master/delivery-sdk-generators">delivery-sdk-generators tool</a>
 *
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * For further modifications of the class, create a separate file and extend this class.
 */
@ContentItemMapping("brand_details")
public class BrandDetails {
  @ElementMapping("logotype_positive_version")
  List<Asset> logotypePositiveVersion;

  @ElementMapping("logotype_negative_version")
  List<Asset> logotypeNegativeVersion;

  @ElementMapping("about_a_company")
  String aboutACompany;

  @ElementMapping("address")
  String address;

  @ElementMapping("telephone")
  String telephone;

  @ElementMapping("email")
  String email;

  @ElementMapping("opening_hours")
  String openingHours;

  @ElementMapping("name")
  String name;

  @ContentItemMapping("promoted_articles")
  List<ContentItem> promotedArticles;

  @ElementMapping("mailing_list")
  String mailingList;

  System system;

  public List<Asset> getLogotypePositiveVersion() {
    return logotypePositiveVersion;
  }

  public void setLogotypePositiveVersion(List<Asset> logotypePositiveVersion) {
    this.logotypePositiveVersion = logotypePositiveVersion;
  }

  public List<Asset> getLogotypeNegativeVersion() {
    return logotypeNegativeVersion;
  }

  public void setLogotypeNegativeVersion(List<Asset> logotypeNegativeVersion) {
    this.logotypeNegativeVersion = logotypeNegativeVersion;
  }

  public String getAboutACompany() {
    return aboutACompany;
  }

  public void setAboutACompany(String aboutACompany) {
    this.aboutACompany = aboutACompany;
  }

  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public String getTelephone() {
    return telephone;
  }

  public void setTelephone(String telephone) {
    this.telephone = telephone;
  }

  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public String getOpeningHours() {
    return openingHours;
  }

  public void setOpeningHours(String openingHours) {
    this.openingHours = openingHours;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public List<ContentItem> getPromotedArticles() {
    return promotedArticles;
  }

  public void setPromotedArticles(List<ContentItem> promotedArticles) {
    this.promotedArticles = promotedArticles;
  }

  public String getMailingList() {
    return mailingList;
  }

  public void setMailingList(String mailingList) {
    this.mailingList = mailingList;
  }

  public System getSystem() {
    return system;
  }

  public void setSystem(System system) {
    this.system = system;
  }
}
