package kontent.ai.sample.android.kotlin.models;

import java.lang.String;
import kontent.ai.delivery.ContentItemMapping;
import kontent.ai.delivery.ElementMapping;
import kontent.ai.delivery.System;

/**
 * This code was generated by a <a href="https://github.com/kontent-ai/java-packages/tree/master/delivery-sdk-generators">delivery-sdk-generators tool</a>
 *
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * For further modifications of the class, create a separate file and extend this class.
 */
@ContentItemMapping("component_feature")
public class ComponentFeature {
  @ElementMapping("icon_class")
  String iconClass;

  @ElementMapping("title")
  String title;

  @ElementMapping("description")
  String description;

  @ElementMapping("feature_link_label")
  String featureLinkLabel;

  @ElementMapping("feature_link_url")
  String featureLinkUrl;

  System system;

  public String getIconClass() {
    return iconClass;
  }

  public void setIconClass(String iconClass) {
    this.iconClass = iconClass;
  }

  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getFeatureLinkLabel() {
    return featureLinkLabel;
  }

  public void setFeatureLinkLabel(String featureLinkLabel) {
    this.featureLinkLabel = featureLinkLabel;
  }

  public String getFeatureLinkUrl() {
    return featureLinkUrl;
  }

  public void setFeatureLinkUrl(String featureLinkUrl) {
    this.featureLinkUrl = featureLinkUrl;
  }

  public System getSystem() {
    return system;
  }

  public void setSystem(System system) {
    this.system = system;
  }
}
