package kontent.ai.sample.android.kotlin.models;

import java.lang.String;
import java.util.List;
import kontent.ai.delivery.Asset;
import kontent.ai.delivery.ContentItemMapping;
import kontent.ai.delivery.ElementMapping;
import kontent.ai.delivery.System;

/**
 * This code was generated by a <a href="https://github.com/kontent-ai/java-packages/tree/master/delivery-sdk-generators">delivery-sdk-generators tool</a>
 *
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * For further modifications of the class, create a separate file and extend this class.
 */
@ContentItemMapping("component_testimonial")
public class ComponentTestimonial {
  @ElementMapping("tagline")
  String tagline;

  @ElementMapping("quote")
  String quote;

  @ElementMapping("author_s_name")
  String authorSName;

  @ElementMapping("author_s_role")
  String authorSRole;

  @ElementMapping("author_s_headshot")
  List<Asset> authorSHeadshot;

  @ElementMapping("illustrative_image")
  List<Asset> illustrativeImage;

  System system;

  public String getTagline() {
    return tagline;
  }

  public void setTagline(String tagline) {
    this.tagline = tagline;
  }

  public String getQuote() {
    return quote;
  }

  public void setQuote(String quote) {
    this.quote = quote;
  }

  public String getAuthorSName() {
    return authorSName;
  }

  public void setAuthorSName(String authorSName) {
    this.authorSName = authorSName;
  }

  public String getAuthorSRole() {
    return authorSRole;
  }

  public void setAuthorSRole(String authorSRole) {
    this.authorSRole = authorSRole;
  }

  public List<Asset> getAuthorSHeadshot() {
    return authorSHeadshot;
  }

  public void setAuthorSHeadshot(List<Asset> authorSHeadshot) {
    this.authorSHeadshot = authorSHeadshot;
  }

  public List<Asset> getIllustrativeImage() {
    return illustrativeImage;
  }

  public void setIllustrativeImage(List<Asset> illustrativeImage) {
    this.illustrativeImage = illustrativeImage;
  }

  public System getSystem() {
    return system;
  }

  public void setSystem(System system) {
    this.system = system;
  }
}
