package kontent.ai.sample.android.kotlin.models;

import java.lang.String;
import java.util.List;
import kontent.ai.delivery.ContentItem;
import kontent.ai.delivery.ContentItemMapping;
import kontent.ai.delivery.ElementMapping;
import kontent.ai.delivery.System;
import kontent.ai.delivery.Taxonomy;

/**
 * This code was generated by a <a href="https://github.com/kontent-ai/java-packages/tree/master/delivery-sdk-generators">delivery-sdk-generators tool</a>
 *
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * For further modifications of the class, create a separate file and extend this class.
 */
@ContentItemMapping("cta")
public class Cta {
  @ContentItemMapping("image")
  List<ContentItem> image;

  @ContentItemMapping("link")
  List<ContentItem> link;

  @ElementMapping("text")
  String text;

  @ElementMapping("internal_description")
  String internalDescription;

  @ElementMapping("persona")
  List<Taxonomy> persona;

  System system;

  public List<ContentItem> getImage() {
    return image;
  }

  public void setImage(List<ContentItem> image) {
    this.image = image;
  }

  public List<ContentItem> getLink() {
    return link;
  }

  public void setLink(List<ContentItem> link) {
    this.link = link;
  }

  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public String getInternalDescription() {
    return internalDescription;
  }

  public void setInternalDescription(String internalDescription) {
    this.internalDescription = internalDescription;
  }

  public List<Taxonomy> getPersona() {
    return persona;
  }

  public void setPersona(List<Taxonomy> persona) {
    this.persona = persona;
  }

  public System getSystem() {
    return system;
  }

  public void setSystem(System system) {
    this.system = system;
  }
}
