package kontent.ai.sample.android.kotlin.models;

import java.util.List;
import kontent.ai.delivery.ContentItem;
import kontent.ai.delivery.ContentItemMapping;
import kontent.ai.delivery.System;

/**
 * This code was generated by a <a href="https://github.com/kontent-ai/java-packages/tree/master/delivery-sdk-generators">delivery-sdk-generators tool</a>
 *
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * For further modifications of the class, create a separate file and extend this class.
 */
@ContentItemMapping("homepage")
public class Homepage {
  @ContentItemMapping("subpages")
  List<ContentItem> subpages;

  System system;

  public List<ContentItem> getSubpages() {
    return subpages;
  }

  public void setSubpages(List<ContentItem> subpages) {
    this.subpages = subpages;
  }

  public System getSystem() {
    return system;
  }

  public void setSystem(System system) {
    this.system = system;
  }
}
