package kontent.ai.sample.android.kotlin.models;

import java.lang.String;
import java.util.List;
import kontent.ai.delivery.Asset;
import kontent.ai.delivery.ContentItem;
import kontent.ai.delivery.ContentItemMapping;
import kontent.ai.delivery.ElementMapping;
import kontent.ai.delivery.System;

/**
 * This code was generated by a <a href="https://github.com/kontent-ai/java-packages/tree/master/delivery-sdk-generators">delivery-sdk-generators tool</a>
 *
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * For further modifications of the class, create a separate file and extend this class.
 */
@ContentItemMapping("insurance_offering")
public class InsuranceOffering {
  @ElementMapping("title")
  String title;

  @ElementMapping("short_description")
  String shortDescription;

  @ElementMapping("illustration")
  String illustration;

  @ElementMapping("product_informatie")
  String productInformatie;

  @ContentItemMapping("wat_verzekert_u_")
  List<ContentItem> watVerzekertU;

  @ElementMapping("polisvoorwaarden")
  List<Asset> polisvoorwaarden;

  System system;

  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public String getShortDescription() {
    return shortDescription;
  }

  public void setShortDescription(String shortDescription) {
    this.shortDescription = shortDescription;
  }

  public String getIllustration() {
    return illustration;
  }

  public void setIllustration(String illustration) {
    this.illustration = illustration;
  }

  public String getProductInformatie() {
    return productInformatie;
  }

  public void setProductInformatie(String productInformatie) {
    this.productInformatie = productInformatie;
  }

  public List<ContentItem> getWatVerzekertU() {
    return watVerzekertU;
  }

  public void setWatVerzekertU(List<ContentItem> watVerzekertU) {
    this.watVerzekertU = watVerzekertU;
  }

  public List<Asset> getPolisvoorwaarden() {
    return polisvoorwaarden;
  }

  public void setPolisvoorwaarden(List<Asset> polisvoorwaarden) {
    this.polisvoorwaarden = polisvoorwaarden;
  }

  public System getSystem() {
    return system;
  }

  public void setSystem(System system) {
    this.system = system;
  }
}
