package kontent.ai.sample.android.kotlin.models;

import java.lang.String;
import java.util.List;
import kontent.ai.delivery.ContentItem;
import kontent.ai.delivery.ContentItemMapping;
import kontent.ai.delivery.ElementMapping;
import kontent.ai.delivery.System;
import kontent.ai.delivery.Taxonomy;

/**
 * This code was generated by a <a href="https://github.com/kontent-ai/java-packages/tree/master/delivery-sdk-generators">delivery-sdk-generators tool</a>
 *
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * For further modifications of the class, create a separate file and extend this class.
 */
@ContentItemMapping("navigation_item")
public class NavigationItem {
  @ElementMapping("title")
  String title;

  @ElementMapping("url")
  String url;

  @ContentItemMapping("subpages")
  List<ContentItem> subpages;

  @ContentItemMapping("content")
  List<ContentItem> content;

  @ElementMapping("sitemap_location")
  List<Taxonomy> sitemapLocation;

  System system;

  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public List<ContentItem> getSubpages() {
    return subpages;
  }

  public void setSubpages(List<ContentItem> subpages) {
    this.subpages = subpages;
  }

  public List<ContentItem> getContent() {
    return content;
  }

  public void setContent(List<ContentItem> content) {
    this.content = content;
  }

  public List<Taxonomy> getSitemapLocation() {
    return sitemapLocation;
  }

  public void setSitemapLocation(List<Taxonomy> sitemapLocation) {
    this.sitemapLocation = sitemapLocation;
  }

  public System getSystem() {
    return system;
  }

  public void setSystem(System system) {
    this.system = system;
  }
}
