package kontent.ai.sample.android.kotlin.models;

import java.lang.String;
import java.util.List;
import kontent.ai.delivery.Asset;
import kontent.ai.delivery.ContentItemMapping;
import kontent.ai.delivery.ElementMapping;
import kontent.ai.delivery.Option;
import kontent.ai.delivery.System;

/**
 * This code was generated by a <a href="https://github.com/kontent-ai/java-packages/tree/master/delivery-sdk-generators">delivery-sdk-generators tool</a>
 *
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * For further modifications of the class, create a separate file and extend this class.
 */
@ContentItemMapping("newsarticle")
public class Newsarticle {
  @ElementMapping("section_introduction__title")
  String sectionIntroductionTitle;

  @ElementMapping("section_introduction__subtitle")
  String sectionIntroductionSubtitle;

  @ElementMapping("section_introduction__description")
  String sectionIntroductionDescription;

  @ElementMapping("seo_metadata__title")
  String seoMetadataTitle;

  @ElementMapping("seo_metadata__description")
  String seoMetadataDescription;

  @ElementMapping("seo_metadata__keywords")
  String seoMetadataKeywords;

  @ElementMapping("seo_metadata__indexing")
  List<Option> seoMetadataIndexing;

  @ElementMapping("seo_metadata__canonical_tags")
  String seoMetadataCanonicalTags;

  @ElementMapping("seo_metadata__og_type")
  String seoMetadataOgType;

  @ElementMapping("seo_metadata__og_image")
  List<Asset> seoMetadataOgImage;

  @ElementMapping("seo_metadata__old_url__301_redirect_")
  String seoMetadataOldUrl301Redirect;

  System system;

  public String getSectionIntroductionTitle() {
    return sectionIntroductionTitle;
  }

  public void setSectionIntroductionTitle(String sectionIntroductionTitle) {
    this.sectionIntroductionTitle = sectionIntroductionTitle;
  }

  public String getSectionIntroductionSubtitle() {
    return sectionIntroductionSubtitle;
  }

  public void setSectionIntroductionSubtitle(String sectionIntroductionSubtitle) {
    this.sectionIntroductionSubtitle = sectionIntroductionSubtitle;
  }

  public String getSectionIntroductionDescription() {
    return sectionIntroductionDescription;
  }

  public void setSectionIntroductionDescription(String sectionIntroductionDescription) {
    this.sectionIntroductionDescription = sectionIntroductionDescription;
  }

  public String getSeoMetadataTitle() {
    return seoMetadataTitle;
  }

  public void setSeoMetadataTitle(String seoMetadataTitle) {
    this.seoMetadataTitle = seoMetadataTitle;
  }

  public String getSeoMetadataDescription() {
    return seoMetadataDescription;
  }

  public void setSeoMetadataDescription(String seoMetadataDescription) {
    this.seoMetadataDescription = seoMetadataDescription;
  }

  public String getSeoMetadataKeywords() {
    return seoMetadataKeywords;
  }

  public void setSeoMetadataKeywords(String seoMetadataKeywords) {
    this.seoMetadataKeywords = seoMetadataKeywords;
  }

  public List<Option> getSeoMetadataIndexing() {
    return seoMetadataIndexing;
  }

  public void setSeoMetadataIndexing(List<Option> seoMetadataIndexing) {
    this.seoMetadataIndexing = seoMetadataIndexing;
  }

  public String getSeoMetadataCanonicalTags() {
    return seoMetadataCanonicalTags;
  }

  public void setSeoMetadataCanonicalTags(String seoMetadataCanonicalTags) {
    this.seoMetadataCanonicalTags = seoMetadataCanonicalTags;
  }

  public String getSeoMetadataOgType() {
    return seoMetadataOgType;
  }

  public void setSeoMetadataOgType(String seoMetadataOgType) {
    this.seoMetadataOgType = seoMetadataOgType;
  }

  public List<Asset> getSeoMetadataOgImage() {
    return seoMetadataOgImage;
  }

  public void setSeoMetadataOgImage(List<Asset> seoMetadataOgImage) {
    this.seoMetadataOgImage = seoMetadataOgImage;
  }

  public String getSeoMetadataOldUrl301Redirect() {
    return seoMetadataOldUrl301Redirect;
  }

  public void setSeoMetadataOldUrl301Redirect(String seoMetadataOldUrl301Redirect) {
    this.seoMetadataOldUrl301Redirect = seoMetadataOldUrl301Redirect;
  }

  public System getSystem() {
    return system;
  }

  public void setSystem(System system) {
    this.system = system;
  }
}
