package kontent.ai.sample.android.kotlin.models;

import java.lang.String;
import java.util.List;
import kontent.ai.delivery.ContentItemMapping;
import kontent.ai.delivery.ElementMapping;
import kontent.ai.delivery.Option;
import kontent.ai.delivery.System;

/**
 * This code was generated by a <a href="https://github.com/kontent-ai/java-packages/tree/master/delivery-sdk-generators">delivery-sdk-generators tool</a>
 *
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * For further modifications of the class, create a separate file and extend this class.
 */
@ContentItemMapping("section_content_carousel")
public class SectionContentCarousel {
  @ElementMapping("section_introduction__title")
  String sectionIntroductionTitle;

  @ElementMapping("section_introduction__subtitle")
  String sectionIntroductionSubtitle;

  @ElementMapping("section_introduction__description")
  String sectionIntroductionDescription;

  @ElementMapping("content_selector")
  List<Option> contentSelector;

  @ElementMapping("number_of_columns")
  List<Option> numberOfColumns;

  System system;

  public String getSectionIntroductionTitle() {
    return sectionIntroductionTitle;
  }

  public void setSectionIntroductionTitle(String sectionIntroductionTitle) {
    this.sectionIntroductionTitle = sectionIntroductionTitle;
  }

  public String getSectionIntroductionSubtitle() {
    return sectionIntroductionSubtitle;
  }

  public void setSectionIntroductionSubtitle(String sectionIntroductionSubtitle) {
    this.sectionIntroductionSubtitle = sectionIntroductionSubtitle;
  }

  public String getSectionIntroductionDescription() {
    return sectionIntroductionDescription;
  }

  public void setSectionIntroductionDescription(String sectionIntroductionDescription) {
    this.sectionIntroductionDescription = sectionIntroductionDescription;
  }

  public List<Option> getContentSelector() {
    return contentSelector;
  }

  public void setContentSelector(List<Option> contentSelector) {
    this.contentSelector = contentSelector;
  }

  public List<Option> getNumberOfColumns() {
    return numberOfColumns;
  }

  public void setNumberOfColumns(List<Option> numberOfColumns) {
    this.numberOfColumns = numberOfColumns;
  }

  public System getSystem() {
    return system;
  }

  public void setSystem(System system) {
    this.system = system;
  }
}
