package kontent.ai.sample.android.kotlin.models;

import java.lang.String;
import java.util.List;
import kontent.ai.delivery.Asset;
import kontent.ai.delivery.ContentItemMapping;
import kontent.ai.delivery.ElementMapping;
import kontent.ai.delivery.System;

/**
 * This code was generated by a <a href="https://github.com/kontent-ai/java-packages/tree/master/delivery-sdk-generators">delivery-sdk-generators tool</a>
 *
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * For further modifications of the class, create a separate file and extend this class.
 */
@ContentItemMapping("section_hero_unit")
public class SectionHeroUnit {
  @ElementMapping("title")
  String title;

  @ElementMapping("description")
  String description;

  @ElementMapping("backdrop_image")
  List<Asset> backdropImage;

  @ElementMapping("cta_button_label")
  String ctaButtonLabel;

  @ElementMapping("cta_button_url")
  String ctaButtonUrl;

  System system;

  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public List<Asset> getBackdropImage() {
    return backdropImage;
  }

  public void setBackdropImage(List<Asset> backdropImage) {
    this.backdropImage = backdropImage;
  }

  public String getCtaButtonLabel() {
    return ctaButtonLabel;
  }

  public void setCtaButtonLabel(String ctaButtonLabel) {
    this.ctaButtonLabel = ctaButtonLabel;
  }

  public String getCtaButtonUrl() {
    return ctaButtonUrl;
  }

  public void setCtaButtonUrl(String ctaButtonUrl) {
    this.ctaButtonUrl = ctaButtonUrl;
  }

  public System getSystem() {
    return system;
  }

  public void setSystem(System system) {
    this.system = system;
  }
}
