package kontent.ai.sample.android.kotlin.models;

import java.lang.String;
import java.util.List;
import kontent.ai.delivery.Asset;
import kontent.ai.delivery.ContentItemMapping;
import kontent.ai.delivery.ElementMapping;
import kontent.ai.delivery.System;

/**
 * This code was generated by a <a href="https://github.com/kontent-ai/java-packages/tree/master/delivery-sdk-generators">delivery-sdk-generators tool</a>
 *
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * For further modifications of the class, create a separate file and extend this class.
 */
@ContentItemMapping("section_about_us")
public class SectionAboutUs {
  @ElementMapping("illustrative_image")
  List<Asset> illustrativeImage;

  @ElementMapping("section_label")
  String sectionLabel;

  @ElementMapping("title")
  String title;

  @ElementMapping("lead_paragraph")
  String leadParagraph;

  @ElementMapping("description")
  String description;

  System system;

  public List<Asset> getIllustrativeImage() {
    return illustrativeImage;
  }

  public void setIllustrativeImage(List<Asset> illustrativeImage) {
    this.illustrativeImage = illustrativeImage;
  }

  public String getSectionLabel() {
    return sectionLabel;
  }

  public void setSectionLabel(String sectionLabel) {
    this.sectionLabel = sectionLabel;
  }

  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public String getLeadParagraph() {
    return leadParagraph;
  }

  public void setLeadParagraph(String leadParagraph) {
    this.leadParagraph = leadParagraph;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public System getSystem() {
    return system;
  }

  public void setSystem(System system) {
    this.system = system;
  }
}
