package kontent.ai.sample.android.kotlin.models;

import java.util.List;
import kontent.ai.delivery.ContentItem;
import kontent.ai.delivery.ContentItemMapping;
import kontent.ai.delivery.System;

/**
 * This code was generated by a <a href="https://github.com/kontent-ai/java-packages/tree/master/delivery-sdk-generators">delivery-sdk-generators tool</a>
 *
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * For further modifications of the class, create a separate file and extend this class.
 */
@ContentItemMapping("section_testimonials_carousel")
public class SectionTestimonialsCarousel {
  @ContentItemMapping("list_of_testimonials")
  List<ContentItem> listOfTestimonials;

  System system;

  public List<ContentItem> getListOfTestimonials() {
    return listOfTestimonials;
  }

  public void setListOfTestimonials(List<ContentItem> listOfTestimonials) {
    this.listOfTestimonials = listOfTestimonials;
  }

  public System getSystem() {
    return system;
  }

  public void setSystem(System system) {
    this.system = system;
  }
}
