package kontent.ai.sample.android.kotlin.models;

import java.lang.String;
import java.util.List;
import kontent.ai.delivery.ContentItem;
import kontent.ai.delivery.ContentItemMapping;
import kontent.ai.delivery.ElementMapping;
import kontent.ai.delivery.System;

/**
 * This code was generated by a <a href="https://github.com/kontent-ai/java-packages/tree/master/delivery-sdk-generators">delivery-sdk-generators tool</a>
 *
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * For further modifications of the class, create a separate file and extend this class.
 */
@ContentItemMapping("topic")
public class Topic {
  @ElementMapping("name")
  String name;

  @ContentItemMapping("related_posts")
  List<ContentItem> relatedPosts;

  System system;

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public List<ContentItem> getRelatedPosts() {
    return relatedPosts;
  }

  public void setRelatedPosts(List<ContentItem> relatedPosts) {
    this.relatedPosts = relatedPosts;
  }

  public System getSystem() {
    return system;
  }

  public void setSystem(System system) {
    this.system = system;
  }
}
