package kontent.ai.sample.android.kotlin.models;

import java.lang.String;
import java.util.List;
import kontent.ai.delivery.ContentItemMapping;
import kontent.ai.delivery.ElementMapping;
import kontent.ai.delivery.Option;
import kontent.ai.delivery.System;

/**
 * This code was generated by a <a href="https://github.com/kontent-ai/java-packages/tree/master/delivery-sdk-generators">delivery-sdk-generators tool</a>
 *
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * For further modifications of the class, create a separate file and extend this class.
 */
@ContentItemMapping("youtube_video")
public class YoutubeVideo {
  @ElementMapping("title")
  String title;

  @ElementMapping("youtube_selector")
  String youtubeSelector;

  @ElementMapping("embed_parameters")
  List<Option> embedParameters;

  System system;

  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public String getYoutubeSelector() {
    return youtubeSelector;
  }

  public void setYoutubeSelector(String youtubeSelector) {
    this.youtubeSelector = youtubeSelector;
  }

  public List<Option> getEmbedParameters() {
    return embedParameters;
  }

  public void setEmbedParameters(List<Option> embedParameters) {
    this.embedParameters = embedParameters;
  }

  public System getSystem() {
    return system;
  }

  public void setSystem(System system) {
    this.system = system;
  }
}
