package kentico.kontent.delivery.sample.dancinggoat.models;

import java.lang.String;
import java.util.List;
import kentico.kontent.delivery.Asset;
import kentico.kontent.delivery.ContentItem;
import kentico.kontent.delivery.ContentItemMapping;
import kentico.kontent.delivery.ElementMapping;
import kentico.kontent.delivery.System;
import kentico.kontent.delivery.Taxonomy;

/**
 * This code was generated by a <a href="https://github.com/Kentico/cloud-generators-java">cloud-generators-java tool</a>
 *
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * For further modifications of the class, create a separate file and extend this class.
 */
@ContentItemMapping("about_us")
public class AboutUs {
  @ElementMapping("metadata__og_description")
  String metadataOgDescription;

  @ElementMapping("metadata__meta_title")
  String metadataMetaTitle;

  @ElementMapping("metadata__og_title")
  String metadataOgTitle;

  @ElementMapping("metadata__meta_description")
  String metadataMetaDescription;

  @ElementMapping("metadata__twitter_site")
  String metadataTwitterSite;

  @ElementMapping("url_pattern")
  String urlPattern;

  @ElementMapping("metadata__twitter_image")
  List<Asset> metadataTwitterImage;

  @ElementMapping("sitemap")
  List<Taxonomy> sitemap;

  @ElementMapping("metadata__twitter_creator")
  String metadataTwitterCreator;

  @ElementMapping("metadata__twitter_title")
  String metadataTwitterTitle;

  @ElementMapping("metadata__twitter_description")
  String metadataTwitterDescription;

  @ElementMapping("metadata__og_image")
  List<Asset> metadataOgImage;

  @ContentItemMapping("facts")
  List<ContentItem> facts;

  System system;

  public String getMetadataOgDescription() {
    return metadataOgDescription;
  }

  public void setMetadataOgDescription(String metadataOgDescription) {
    this.metadataOgDescription = metadataOgDescription;
  }

  public String getMetadataMetaTitle() {
    return metadataMetaTitle;
  }

  public void setMetadataMetaTitle(String metadataMetaTitle) {
    this.metadataMetaTitle = metadataMetaTitle;
  }

  public String getMetadataOgTitle() {
    return metadataOgTitle;
  }

  public void setMetadataOgTitle(String metadataOgTitle) {
    this.metadataOgTitle = metadataOgTitle;
  }

  public String getMetadataMetaDescription() {
    return metadataMetaDescription;
  }

  public void setMetadataMetaDescription(String metadataMetaDescription) {
    this.metadataMetaDescription = metadataMetaDescription;
  }

  public String getMetadataTwitterSite() {
    return metadataTwitterSite;
  }

  public void setMetadataTwitterSite(String metadataTwitterSite) {
    this.metadataTwitterSite = metadataTwitterSite;
  }

  public String getUrlPattern() {
    return urlPattern;
  }

  public void setUrlPattern(String urlPattern) {
    this.urlPattern = urlPattern;
  }

  public List<Asset> getMetadataTwitterImage() {
    return metadataTwitterImage;
  }

  public void setMetadataTwitterImage(List<Asset> metadataTwitterImage) {
    this.metadataTwitterImage = metadataTwitterImage;
  }

  public List<Taxonomy> getSitemap() {
    return sitemap;
  }

  public void setSitemap(List<Taxonomy> sitemap) {
    this.sitemap = sitemap;
  }

  public String getMetadataTwitterCreator() {
    return metadataTwitterCreator;
  }

  public void setMetadataTwitterCreator(String metadataTwitterCreator) {
    this.metadataTwitterCreator = metadataTwitterCreator;
  }

  public String getMetadataTwitterTitle() {
    return metadataTwitterTitle;
  }

  public void setMetadataTwitterTitle(String metadataTwitterTitle) {
    this.metadataTwitterTitle = metadataTwitterTitle;
  }

  public String getMetadataTwitterDescription() {
    return metadataTwitterDescription;
  }

  public void setMetadataTwitterDescription(String metadataTwitterDescription) {
    this.metadataTwitterDescription = metadataTwitterDescription;
  }

  public List<Asset> getMetadataOgImage() {
    return metadataOgImage;
  }

  public void setMetadataOgImage(List<Asset> metadataOgImage) {
    this.metadataOgImage = metadataOgImage;
  }

  public List<ContentItem> getFacts() {
    return facts;
  }

  public void setFacts(List<ContentItem> facts) {
    this.facts = facts;
  }

  public System getSystem() {
    return system;
  }

  public void setSystem(System system) {
    this.system = system;
  }
}
