package kentico.kontent.delivery.nestedmodels;

import kentico.kontent.delivery.ContentItemMapping;
import kentico.kontent.delivery.ElementMapping;
import kentico.kontent.delivery.System;

import java.util.List;

/**
 * This code was generated by a <a href="https://github.com/Kentico/cloud-generators-java">cloud-generators-java tool</a>
 *
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * For further modifications of the class, create a separate file and extend this class.
 */
@ContentItemMapping("section")
public class Section {
  @ContentItemMapping("section_parts")
  List<SectionPart> sectionParts;

  @ElementMapping("headline")
  String headline;

  System system;

  public List<SectionPart> getSectionParts() {
    return sectionParts;
  }

  public void setSectionParts(List<SectionPart> sectionParts) {
    this.sectionParts = sectionParts;
  }

  public String getHeadline() {
    return headline;
  }

  public void setHeadline(String headline) {
    this.headline = headline;
  }

  public System getSystem() {
    return system;
  }

  public void setSystem(System system) {
    this.system = system;
  }
}
